
from gdascripts.parameters import beamline_parameters

jythonNameMap = beamline_parameters.JythonNameSpaceMapping()
flux_utils = jythonNameMap.flux_utils

def calculate_absorption_coefficient(energy_electron_volts):
	return flux_utils.dose_utils.calculate_mu_absorption(energy_electron_volts)

def calculate_dataset_dose_megagray(exposure_seconds, energy_electron_volts, horiz_diameter_microns, vert_diameter_microns, beamline_transmission_percentage=100):
	flux_photons_per_second = predict_photons_per_second(energy_electron_volts, horiz_diameter_microns, vert_diameter_microns, beamline_transmission_percentage)
	return exposure_seconds * flux_utils.dose_utils.calculate_dose_rate(flux_photons_per_second, horiz_diameter_microns, vert_diameter_microns, energy_electron_volts)

def predict_photons_per_second(energy_electron_volts, horiz_diameter_microns, vert_diameter_microns, beamline_transmission_percentage=100):
	return flux_utils.predict_flux_by_beamsize(energy_electron_volts, beamline_transmission_percentage, horiz_diameter_microns, vert_diameter_microns)
